### ISSUE TITLE
Issue with connection of wallet using WalletConnect QR Code

### ISSUE THREAD

**Issue by olehbairak** [NethermindEth/zksync-remix-plugin#65]
Currently when user tries to connect wallet by using WalletConnect QR code there's an error
STR:
1. Open zkSync Remix plugin
2. In Environment section - Click on Dropdown "Environment selection"
3. Choose "Wallet"
4. Click on "Connect Wallet"
5. Choose "WalletConnect" option
6. Scan opened QR code with wallet app (e.g. MetaMask)

Expected result: Wallet should be connected
Actual result: Connection is not established, console error is present.

Console error text:
`index.es-862680dc.js:1 Error: User rejected methods.
    at index.es-862680dc.js:27:38438
    at async o (index.es-862680dc.js:27:38241)`

<img width="1683" alt="image" src="https://github.com/NethermindEth/zksync-remix-plugin/assets/118197764/9ee8e910-33a1-4626-aaf7-ea5969c5cdc0">

Example of error that shows Rainbow wallet:

![telegram-cloud-photo-size-2-5305312276431099781-y](https://github.com/NethermindEth/zksync-remix-plugin/assets/118197764/7994ae47-3df1-4b6b-948a-6a163d2c2f3a)

**Comment by varex83** [comment]
It seems to me that Rainbow wallet doesn't support the zksync mainnet / testnet, I've also tested it with Trust Wallet, and it connects to zksync mainnet, but not testnet

**Comment by olehbairak** [comment]
> It seems to me that Rainbow wallet doesn't support the zksync mainnet / testnet, I've also tested it with Trust Wallet, and it connects to zksync mainnet, but not testnet

But the same issue is present for MM wallet, that should support Era Test and Mainnet networks.
I re-checked on [Portal](https://portal.zksync.io/bridge/?network=goerli) and WalletConnect works ok with MM (same wallet as I used for testing Remix plugin).

**Comment by varex83** [comment]
Got it, I will dive into it more
